name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Set up Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: npm install

      - name: Sync Capacitor Android
        run: |
          npx cap android add || true
          npx cap sync android

      - name: Build Android App Bundle / APK
        run: |
          if [ -d "android" ]; then
            cd android
            ./gradlew assembleDebug
          else
            echo "Error: No se pudo generar la carpeta nativa de Android" && exit 1
          fi

      - name: Upload APK Package
        uses: actions/upload-artifact@v4
        with:
          name: Stream-Ocations-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
